name: AntoineManceaux
favicon: null
layout_spectrum: 0.653633720939979
typography_spectrum: 0.9013419083785266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#05060f'
    - '#5e6770'
    - '#779bc2'
    - '#bbeeff'
    - '#a1c3e7'
  brandStrength: 0.3125
  lightness: 0.8119371908251196
  saturation: 0.5816762857139111
  rhythmicContrast: 0.991645151283592
purpose: []
